version: '3.8'

services:
  goapp:
    build: .
    container_name: golang-grpc
    ports:
      - '8080:8080'
    volumes:
    - .:/app
    networks:
      - databases-network-dev

networks:
    databases-network-dev:
      driver: bridge
